version: '3.8'

services:
  php:
    build:
      dockerfile: ./php/Dockerfile
      context: ./
    restart: always
    ports:
      - 10080:80
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: root
    volumes:
      - ../php:/var/www/html/team-portal
      - ./php/.htaccess:/var/www/html/.htaccess
      - ./php/php-development.ini:/usr/local/etc/php/php.ini
      - type: bind
        source: ./php/www-root
        target: /var/www/html

  mysql:
    image: mysql:5.6
    command:
      - --max_allowed_packet=256M
      - --innodb-log-file-size=100M
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 200M
    ports:
      - '10081:80'

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 18025:8025
      - 11025:1025
