version: '3'

services:
  # Database
  mysql:
    image: mysql:5.7
    command:
      - --max_allowed_packet=256M
      - --innodb-log-file-size=100M
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root


  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '10081:80'


  # Wordpress
  wordpress:
    build: . 
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./public_html/:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 18025:8025 # web ui
      - 11025:1025 # smtp server

volumes:
  db_data: