on:
  workflow_dispatch:
  push: 
    branches: 
      - dev
name: 🚀 Deploy Team-Portal to test
jobs:
  Deploy-Team-Portal-to-Test: 
    name: Deploy Team-Portal to test on host
    runs-on: ubuntu-latest
    steps:
    - name: Curl whitelist Github Runner IP at Antagonist
      run: |
        curl icanhazip.com > runner_ip.txt
        runner_ip=$(cat runner_ip.txt)
        curl --location --request POST 'https://skcvolleybal.nl:2223/CMD_PLUGINS/ssh?iframe=yes' --header 'Authorization: Basic ${{ secrets.base64_username_colon_password_antagonist }}' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'ip='"$runner_ip"'' --data-urlencode 'expires=1800' --data-urlencode 'sshkey=5f:8d:bd:86:30:7e:cf:5c:8d:a1:c2:bd:c0:8b:af:53' --data-urlencode 'newkey_title= ' --data-urlencode 'newkey_key= ' --data-urlencode 'add_key_ip=Voeg IP toe aan key'
    - name: 🏗️ Get latest code
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: 🏗️ Installing NPM dependencies
      run: npm i -f
    - name: 🔨 Building Angular
      run: npm run test_deploy
    # - name: 🏗️ Installing PHP dependencies
    #   run: |
    #     composer update --ignore-platform-reqs --working-dir=php
    #     composer dumpautoload --working-dir=php
    - name: Install dependencies
      uses: php-actions/composer@master
      with:
        php_version: "8.0"
        command: install
        args: --ignore-platform-reqs --working-dir=php
    - name: Prepare package
      run: |
        mv php/ dist/
        mv static-pages/ dist/
        mv php/configuration_example.php configuration.php
    - name: 🚚 Transfer files to webhost 
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude="configuration.php"
        path: dist/*
        remote_path: public_html/test/public_html/team-portal/
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.PRIVATE_KEY }}