on:
  workflow_dispatch:
  push: 
    branches: 
      - dev
name: 🚀 Deploy Team-Portal to test
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 🔎 Show Github Runner IP
        if: always()
        run: curl https://api.ipify.org
      - name: You have 30 seconds to add the Github Runner IP to Antagonist SSH key!
        run: |
          echo "For the IP: see previous step ('Show Github Runner IP'). Then, go to https://skcvolleybal.nl:2223/user/plugins/ssh and add the IP to 'Github Runner Key Antagonist. '
          sleep 30s
        shell: bash
        # Continue
      - uses: actions/setup-node@master
      - name: 🏗️ Installing NPM dependencies
        run: npm i -f
      - name: 🔨 Building Angular
        run: npm run build
      - name: 🏗️ Installing PHP dependencies
        run: composer update --ignore-platform-reqs --working-dir=php
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./  
          remote_path: public_html/test/public_html/team-portal/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.skcvolleybal.nl
          username: ${{ secrets.test_ftp_username }}
          password: ${{ secrets.test_ftp_password }}
        # Server-dir not necessary: the FTP account only has rights to write in test/public_html/team-portal. See webhost control panel for FTP. 