on:
  workflow_dispatch:
  push: 
    branches: 
      - dev
name: 🚀 Deploy Team-Portal to test
jobs:
  Deploy-Team-Portal-to-Test: 
    name: Deploy Team-Portal to test on host
    runs-on: ubuntu-latest
    steps:
    - name: 🔎 Get Github Runner IP
      run: curl icanhazip.com > ../.runner_ip.txt
    - name: Assign IP to variable
      run: runner_ip=$( cat ../.runner_ip.txt )
    - name: Curl whitelist Github Runner IP at Antagonist
      run: curl --location --request POST 'https://skcvolleybal.nl:2223/CMD_PLUGINS/ssh?iframe=yes' --header 'Authorization: Basic ${{ secrets.base64_username_colon_password_antagonist }}' --header 'Content-Type: application/x-www-form-urlencoded' --header  --data-urlencode 'ip=\"$runner_ip\"' --data-urlencode 'expires=180' --data-urlencode 'sshkey=5f:8d:bd:86:30:7e:cf:5c:8d:a1:c2:bd:c0:8b:af:53' --data-urlencode 'newkey_title= ' --data-urlencode 'newkey_key= ' --data-urlencode 'add_key_ip=Voeg IP toe aan key'
    # - name: 🔎 Show Github Runner IP
    #   if: always()
    #   run: curl https://api.ipify.org
    # - name: ⚠️ You now have 30 seconds to add the Github Runner IP to Antagonist SSH key!
    #   run: |
    #     echo "For the IP: see previous step ('Show Github Runner IP'). Then, go to https://skcvolleybal.nl:2223/user/plugins/ssh and add the IP to 'Github Runner Key Antagonist."
    #     sleep 30s
    #   shell: bash
    # - name: 🏗️ Get latest code
    #   uses: actions/checkout@v2
    # - uses: actions/setup-node@master
    # - name: 🏗️ Installing NPM dependencies
    #   run: npm i -f
    # - name: 🔨 Building Angular
    #   run: npm run build
    # - name: 🏗️ Installing PHP dependencies
    #   run: |
    #     composer update --ignore-platform-reqs --working-dir=php
    #     composer dumpautoload --working-dir=php
    # - name: Prepare package
    #   run: |
    #     mv php/ dist/
    #     mv static-pages/ dist/
    # - name: 🚚 Transfer files to webhost 
    #   uses: burnett01/rsync-deployments@5.2.1
    #   with:
    #     switches: -avzr --delete --exclude="configuration.php"
    #     path: dist/*
    #     remote_path: public_html/test/public_html/team-portal/
    #     remote_host: ${{ secrets.REMOTE_HOST }}
    #     remote_user: ${{ secrets.REMOTE_USER }}
    #     remote_key: ${{ secrets.PRIVATE_KEY }}