on:
  workflow_dispatch:
  push: 
    branches: 
      - dev
name: 🚀 Deploy Team-Portal to test
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci
    - name: Build
      run: |
        npm run build -- --prod
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm run test -- --prod
    - name: Installing PHP dependencies
      run: composer update --ignore-platform-reqs
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.skcvolleybal.nl
        username: ${{ secrets.test_ftp_username }}
        password: ${{ secrets.test_ftp_password }}
        # Server-dir not necessary: the FTP account only has rights to write in test/public_html/team-portal. See webhost control panel for FTP. 