on:
  workflow_dispatch:
  push: 
    branches: 
      - dev
name: 🚀 Deploy Team-Portal to test
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: Check Antagonist SSH
        - if: always()
        - run: echo "Did the previous job (Rsync) fail? Make sure you've whitelisted the current GitHub Runners IP in Antagonist SSH key. Go to https://skcvolleybal.nl:2223/user/plugins/ssh and add the following IP address to the 'Github Runner Key Antagonist --> "
      - name: 🔎 Show Github Runner IP
        if: always()
        run: curl https://api.ipify.org
      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
      #   with:
      #     server: ftp.skcvolleybal.nl
      #     username: ${{ secrets.test_ftp_username }}
      #     password: ${{ secrets.test_ftp_password }}
        # Server-dir not necessary: the FTP account only has rights to write in test/public_html/team-portal. See webhost control panel for FTP. 